arxiv1:
  dataset: Arxiv
  mask: Path
  encoder_hidden: 256
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.2
  decoder_hidden: 32
  decoder_layers: 4
  decoder_dropout: 0.01
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.39
  nb_size: 10
  knn_nb: 10
  ncaps: 16
  nlayer: 3
  max_iter: 5
  hsic_lamb: 0.000014  #{0.000005:16,0.000008:15, 0.000009:12, 0.00001:8, 1.2e-05:4, 0.000014:1, 0.000015:0, 0.00002:0, 0.00007:0, 0.0001:0}
  link_lr_max: 0.0005
  link_lr_min: 0.0005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1
  original_lamb: 0.42
  new_lamb: 1.0
  recon_alpha: 0.38
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 0.0001
  nodeclas_weight_decay: 0
  eval_period: 1
  patience: 200
  save_path: model_nodeclas.pth
  epochs: 20

photo1:
  dataset: Photo
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.62
  decoder_hidden: 32
  decoder_layers: 4
  decoder_dropout: 0.31
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.39
  nb_size: 50
  knn_nb: 50
  ncaps: 32
  nlayer: 6
  max_iter: 8
  hsic_lamb: 0.000311
  link_lr_max: 0.005
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1
  original_lamb: 0.42
  new_lamb: 1.0
  recon_alpha: 0.38
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 1.9e-05
  nodeclas_weight_decay: 2e-05
  eval_period: 1
  patience: 200
  save_path: model_nodeclas.pth
  epochs: 180

computers1:
  ncaps: 32
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.55
  decoder_hidden: 64
  decoder_layers: 3
  decoder_dropout: 0.35
  ch_decoder_layers: 2
  ch_decoder_dropout: 0.11
  nb_size: 50
  knn_nb: 30
  nlayer: 6
  max_iter: 8
  hsic_lamb: 1.7e-04 # 6.5e-05: 19   1.5e-04: 3
  link_lr_max: 0.01
  link_lr_min: 0.001
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  l2_normalize: True
  alpha_l: 1
  original_lamb: 0.5
  new_lamb: 1.0
  recon_alpha: 0.32
  weight_decay: 8.26e-05
  nodeclas_weight_decay: 3.0e-06
  epochs: 180 #200

wikics1:
  ncaps: 32
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.58
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.74
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.34
  nb_size: 30
  knn_nb: 40
  nlayer: 6
  max_iter: 8
  hsic_lamb: 4.0e-05 # 6.5e-05: 19   1.5e-04: 3
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  l2_normalize: True
  alpha_l: 1
  original_lamb: 0.5
  new_lamb: 1.0
  recon_alpha: 0.18
  weight_decay: 8.83e-05
  nodeclas_weight_decay: 4.92e-05
  epochs: 180 #200



cora1:
  dataset: Cora
  # beta 1  4
  # beta 2  1
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.69
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.26
  ch_decoder_layers: 2
  ch_decoder_dropout: 0.51
  nb_size: 50
  knn_nb: 50
  ncaps: 16
  nlayer: 6
  max_iter: 9
  hsic_lamb: 9.5e-04
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.01
  node_lr_min: 0.01
  grad_norm: 1.0
  original_lamb: 0.8
  new_lamb: 1.0
  recon_alpha: 0.5
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 5.5e-05
  nodeclas_weight_decay: 0.001
  epochs: 87 # 1shot: 110
  eval_period: 1
  patience: 150
  save_path: model_nodeclas.pth
  bn: True



citeseer1:
  dataset: Citeseer
  # beta 1  5
  # beta 2  2
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.63
  decoder_hidden: 32
  decoder_layers: 4
  decoder_dropout: 0.16
  ch_decoder_layers: 1
  ch_decoder_dropout: 0.47
  nb_size: 40
  knn_nb: 60
  ncaps: 16
  nlayer: 4
  max_iter: 6
  hsic_lamb: 2.8e-06
  link_lr_max: 0.01 #0.01 for edge   # 0.001 for cluster
  link_lr_min: 0.01 #0.01 for edge   # 0.001 for cluster
  node_lr_max: 0.01
  node_lr_min: 0.01
  grad_norm: 1.0
  original_lamb: 0.69
  new_lamb: 1.0
  recon_alpha: 0.67
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 0.00018
  nodeclas_weight_decay: 0.11
  epochs: 100 # 131 # 1shot: 140
  eval_period: 1
  patience: 150
  save_path: model_nodeclas.pth
  alpha_1: 1

pubmed1:
  dataset: Pubmed
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.54
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.49
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.16
  nb_size: 40
  knn_nb: 50
  ncaps: 16
  nlayer: 8
  max_iter: 7
  hsic_lamb: 2.4e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  original_lamb: 0.4
  new_lamb: 1.0
  recon_alpha: 0.69
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 0.00086
  nodeclas_weight_decay: 0.001
  epochs: 300
  eval_period: 1
  patience: 150
  save_path: model_nodeclas.pth
