cora1:
  dataset: Cora
  mask: Path
  device: 3
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.31
  decoder_hidden: 32
  decoder_layers: 3
  decoder_dropout: 0.37
  ch_decoder_layers: 3
  ch_decoder_dropout: 0.31
  nb_size: 40
  knn_nb: 30
  ncaps: 16
  nlayer: 5
  max_iter: 9
  hsic_lamb: 2.61e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  original_lamb: 0.2
  new_lamb: 1.0
  recon_alpha: 0.2
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 6e-06
  nodeclas_weight_decay: 0.0063
  epochs: 350
  eval_period: 1
  patience: 250
  save_path: model_nodeclas.pth
  bn: True

citeseer1:
  seed: 0
  dataset: Citeseer
  mask: Path
  device: 6
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.54
  decoder_hidden: 64
  decoder_layers: 2
  decoder_dropout: 0.67
  ch_decoder_layers: 3
  ch_decoder_dropout: 0.33
  nb_size: 50
  knn_nb: 40
  ncaps: 32
  nlayer: 5
  max_iter: 10
  hsic_lamb: 4.43e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  original_lamb: 0.5
  new_lamb: 1.0
  recon_alpha: 0.61
  batch_size: 65536
  l2_normalize: False
  alpha_l: 1
  weight_decay: 0.000144
  nodeclas_weight_decay: 0.18
  epochs: 200
  eval_period: 1
  patience: 250
  save_path: model_nodeclas.pth

pubmed1:
  seed: 0
  dataset: Pubmed
  mask: Path
  device: 0
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.46
  decoder_hidden: 64
  decoder_layers: 3
  decoder_dropout: 0.57
  ch_decoder_layers: 2
  ch_decoder_dropout: 0.27
  nb_size: 70
  knn_nb: 60
  ncaps: 32
  nlayer: 4
  max_iter: 9
  hsic_lamb: 0.000263
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  original_lamb: 0.6
  new_lamb: 1.0
  recon_alpha: 0.3
  batch_size: 65536
  l2_normalize: False
  alpha_l: 3
  weight_decay: 8e-05
  nodeclas_weight_decay: 0.001
  epochs: 200
  eval_period: 1
  patience: 300
  save_path: model_nodeclas.pth
