photo1:
  dataset: Photo
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.62
  decoder_hidden: 32
  decoder_layers: 4
  decoder_dropout: 0.31
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.39
  nb_size: 50
  knn_nb: 50
  ncaps: 32
  nlayer: 6
  max_iter: 8
  hsic_lamb: 0.000311
  link_lr_max: 0.005
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1
  original_lamb: 0.42
  new_lamb: 1.0
  recon_alpha: 0.38
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 1.9e-05
  nodeclas_weight_decay: 2e-05
  eval_period: 1
  patience: 200
  save_path: model_nodeclas.pth
  epochs: 180

computers1:
  ncaps: 32
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.55
  decoder_hidden: 64
  decoder_layers: 3
  decoder_dropout: 0.35
  ch_decoder_layers: 2
  ch_decoder_dropout: 0.11
  nb_size: 50
  knn_nb: 30
  nlayer: 6
  max_iter: 8
  hsic_lamb: 1.7e-04 # 6.5e-05: 19   1.5e-04: 3
  link_lr_max: 0.01
  link_lr_min: 0.001
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  l2_normalize: True
  alpha_l: 1
  original_lamb: 0.5
  new_lamb: 1.0
  recon_alpha: 0.32
  weight_decay: 8.26e-05
  nodeclas_weight_decay: 3.0e-06
  epochs: 180 #200

wikics1:
  ncaps: 32
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.58
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.74
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.34
  nb_size: 30
  knn_nb: 40
  nlayer: 6
  max_iter: 8
  hsic_lamb: 4.0e-05 # 6.5e-05: 19   1.5e-04: 3
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  l2_normalize: True
  alpha_l: 1
  original_lamb: 0.5
  new_lamb: 1.0
  recon_alpha: 0.18
  weight_decay: 8.83e-05
  nodeclas_weight_decay: 4.92e-05
  epochs: 180 #200


cora1:
  dataset: Cora
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.8
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.49
  ch_decoder_layers: 2
  ch_decoder_dropout: 0.38
  nb_size: 30
  knn_nb: 40
  ncaps: 16
  nlayer: 6
  max_iter: 9
  hsic_lamb: 4.3e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  original_lamb: 0.8
  new_lamb: 1.0
  recon_alpha: 0.138
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 4.3e-05
  nodeclas_weight_decay: 0.0053
  epochs: 300
  eval_period: 1
  patience: 150
  save_path: model_nodeclas.pth
  bn: True

citeseer1:
  dataset: Citeseer
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.79
  decoder_hidden: 32
  decoder_layers: 4
  decoder_dropout: 0.22
  ch_decoder_layers: 1
  ch_decoder_dropout: 0.52
  nb_size: 40
  knn_nb: 60
  ncaps: 16
  nlayer: 4
  max_iter: 6
  hsic_lamb: 2.9e-06
  link_lr_max: 0.01
  link_lr_min: 0.01
  node_lr_max: 0.01
  node_lr_min: 0.01
  grad_norm: 1.0
  original_lamb: 0.9
  new_lamb: 1.0
  recon_alpha: 0.58
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 0.00017
  nodeclas_weight_decay: 0.08
  epochs: 200
  eval_period: 1
  patience: 150
  save_path: model_nodeclas.pth
  alpha_1: 1

pubmed1:
  dataset: Pubmed
  mask: Path
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.54
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.49
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.16
  nb_size: 40
  knn_nb: 50
  ncaps: 16
  nlayer: 8
  max_iter: 7
  hsic_lamb: 2.4e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  original_lamb: 0.4
  new_lamb: 1.0
  recon_alpha: 0.69
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 0.00086
  nodeclas_weight_decay: 0.001
  epochs: 200
  eval_period: 1
  patience: 150
  save_path: model_nodeclas.pth
